version: "3.7"

services:
  app:
    container_name: pasha-hackathon
    image: pasha-hackathon:lates
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/hackathon
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=secret
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: postgres
    restart: always
    container_name: pasha-db
    ports:
      - '5432:5432'
    environment:
       POSTGRES_DB: hackathon
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: secret

