spring:
  datasource:
    url: ${POSTGRES_DB_URL:jdbc:postgresql://db:5432/hackathon}
    username: ${POSTGRES_DB_USERNAME:postgres}
    password: ${POSTGRES_DB_PASSWORD:secret}

  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  application:
    name: intro-spring-boot

#
#app:
#  jwt-secret: JWTSecretKey
#  jwt-expiration-milliseconds: 604800000
server:
  port: 8081
